### ISSUE TITLE
Spice on SmartOS guide is incorrect

### ISSUE THREAD

**Issue by Ethan-Arrowood** [TritonDataCenter/smartos-live#1073]
I'm trying to get Spice working on my emulated SmartOS environment. I'm following this guide: https://docs.smartos.org/spice-on-smartos/ and when I run the install command: `imgadm sources -a http://datasets.shalman.org/datasets -t dsapi` I'm met with the error: 

<img width="738" alt="Screenshot 2023-04-19 at 8 53 09 PM" src="https://user-images.githubusercontent.com/16144158/233246070-1bb8ea8b-7aa4-47f2-85b6-22ccb4fb71ff.png">

Any ideas?

**Comment by bahamat** [comment]
Looks like that server (run by community member @nshalman) is no longer working.

Please note, that the top of that page says that it's not supported. It was something created only by the community.

Considering that any effort on spice was abandoned nearly a decade ago, I'm going to just delete those pages because they're causing more harm than good anymore.

**Comment by nshalman** [comment]
FWIW there was a very subtle bug in my image server that was exposed by a nodejs update. I have since fixed it. Those (ancient at this point) images are once again available, though unmaintained, so deleting the page was a good idea.
The information is still there in the git history if we ever want to resurrect it.
