### ISSUE TITLE
bhyve: update to newer ed2k firmware

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/smartos-live#975]
https://github.com/illumos/uefi-edk2/releases/

Andy did some testing and asked me to verify, these new firmwares seem to work fine with any combination of ppt, vnc, nvme,... we throw at them. 

I've been running on various iterations of this firmware and the last few months it's been stable without any issues, it would be great to update the ones SmartOS ships to these ones.

**Comment by papertigers** [comment]
I will try to take a look this week. 

You tested with a variety of OSes?

**Comment by sjorge** [comment]
I retested the particular andy was tested on Windows 10, FreeBSD, and OmniOS.

**Comment by sjorge** [comment]
Have you had a chance to look at this?

**Comment by sjorge** [comment]
@papertigers after upgrading some VM's to FreeBSD 13... the newer firmware is now a must.
With the older firmware the loader has issues, also shutdown doesn't work... the VM just keeps running.

With the newer firmware, loader looks good and the vm shuts down properly (both from within the guest and via vmadm stop)

**Comment by papertigers** [comment]
@bahamat btw here's the open ticket for it.

**Comment by GernotS** [comment]
May I kindly ask for the status of this? 
All Windows version are unable to boot using bhve nvme without a newer UEFI (like https://downloads.omnios.org/misc/bhyve/BHYVE_RELEASE.fd)

thanks

**Comment by danmcd** [comment]
We went down a rabbit hole for a bit about whether or not we can/should build at least the UEFI-only one (since the CSM one cannot change since its old one) in illumos-extra.  We can't at the moment, but we can refresh the UEFI-only one in smartos-live with a fresh one.  Please contact me if you're interested in a test PI with it.

**Comment by GernotS** [comment]
Hi Dan,

 

you already know I test almost everything 😊

The UEFI binary alone would be sufficient for me as I build Smartos myself anyways. 

 

thanks

Regards

Gernot

 

 

Von: Dan McDonald ***@***.***> 
Gesendet: Samstag, 24. Februar 2024 15:09
An: TritonDataCenter/smartos-live ***@***.***>
Cc: GernotS ***@***.***>; Comment ***@***.***>
Betreff: Re: [TritonDataCenter/smartos-live] bhyve: update to newer ed2k firmware (#975)

 

We went down a rabbit hole for a bit about whether or not we can/should build at least the UEFI-only one (since the CSM one cannot change since its old one) in illumos-extra. We can't at the moment, but we can refresh the UEFI-only one in smartos-live with a fresh one. Please contact me if you're interested in a test PI with it.
